In [1]:
import numpy as np

# 행렬만들기

## 일반행렬

In [2]:
x=np.array([[1,2,3,4],[5,6,7,8]])
print(x)

[[1 2 3 4]
 [5 6 7 8]]


## 단위행렬 eye

In [3]:
e=np.eye(4)
print(e)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


## 영행렬 zero

In [4]:
x=np.zeros((4,4))
print(x)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


## 1행렬 ones

In [5]:
x=np.ones((4,4))
print(x)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


## 대각행렬 diag

In [6]:
x=np.arange(9).reshape(3,3)
print(x)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [7]:
y=np.diag(x)
print(y)

[0 4 8]


In [8]:
print(np.diag(np.diag(x)))

[[0 0 0]
 [0 4 0]
 [0 0 8]]


## 전치행렬

In [9]:
x=np.arange(10).reshape(2,5)
print(x)

[[0 1 2 3 4]
 [5 6 7 8 9]]


In [10]:
print(x.T)

[[0 5]
 [1 6]
 [2 7]
 [3 8]
 [4 9]]


In [11]:
print(np.transpose(x))

[[0 5]
 [1 6]
 [2 7]
 [3 8]
 [4 9]]


## 내적 np.dot(a,b) a.dot(b)

In [12]:
x=np.array([[1,2],[2,3]])
print(x)

[[1 2]
 [2 3]]


In [13]:
print(x*x)

[[1 4]
 [4 9]]


In [14]:
print(np.dot(x,x))

[[ 5  8]
 [ 8 13]]


## 대각합
- 정방 행렬의 대각에위치한 원소를 전부 더해준다

In [15]:
x=np.arange(16).reshape(4,-1)
print(x)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]


In [16]:
print(np.trace(x))

30


In [17]:
x=np.arange(1,28).reshape(3,3,3)
print(x)

[[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]]

 [[10 11 12]
  [13 14 15]
  [16 17 18]]

 [[19 20 21]
  [22 23 24]
  [25 26 27]]]


In [18]:
print(np.trace(x))

[39 42 45]
