# 확률 분포에 따른 ndarray 생성하기
1. uniform : 로우에서 하이값 사이를 가져와 ndarray를 생성
2. normal : 정규분포(randn)과 같은 결과

In [2]:
import numpy as np
x= np.random.uniform(1.0,3.0, size=(4,5))
print(x)

[[2.03141557 2.43776597 2.38368882 1.11317665 1.93566295]
 [1.2952686  1.17328382 1.45476516 1.88170914 1.53751568]
 [2.57358555 1.46326096 1.19700208 1.40109101 2.15108681]
 [1.75640926 2.74027434 2.74181229 2.99397638 1.44233687]]


In [3]:
y=np.random.normal(size=(4,5))
print(y)

[[ 0.73032359  0.37155065 -0.23313048  0.65399676 -0.0111651 ]
 [ 1.16885762  0.48975433 -2.12218599 -2.12428068  0.79650682]
 [ 0.5292505  -0.78552496  1.19759313 -2.72654097 -1.25200532]
 [-0.01116538 -1.38005161  1.49373939  0.78862709  0.08185575]]


## 인덱싱

In [5]:
L=[1,2,3,4,5]
print(L[2])

3


In [6]:
x=np.arange(10)
print(x)
print(x[3])
x[3]=100
print(x)

[0 1 2 3 4 5 6 7 8 9]
3
[  0   1   2 100   4   5   6   7   8   9]


In [8]:
x=np.arange(10).reshape(2,5)
print(x)

[[0 1 2 3 4]
 [5 6 7 8 9]]


In [9]:
print(x[0])

[0 1 2 3 4]


In [12]:
print(x[0,1])
print(x[1][-1])

1
9


In [13]:
x=np.arange(36).reshape(3,4,3)
print(x)
print(x[0])

[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]
  [ 9 10 11]]

 [[12 13 14]
  [15 16 17]
  [18 19 20]
  [21 22 23]]

 [[24 25 26]
  [27 28 29]
  [30 31 32]
  [33 34 35]]]
[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]


In [14]:
print(x[0,1])

[3 4 5]
