In [1]:
import numpy as np
import time

n=150
matA = np.array(np.random.rand(n,n))
matA

array([[0.03663527, 0.8872376 , 0.70164294, ..., 0.12673496, 0.08849538,
        0.83145533],
       [0.91865304, 0.96217537, 0.87616132, ..., 0.61652735, 0.91854824,
        0.04502347],
       [0.38634389, 0.47459353, 0.42660964, ..., 0.95211808, 0.3776781 ,
        0.38187596],
       ...,
       [0.43206557, 0.96224181, 0.66562426, ..., 0.71500159, 0.6872594 ,
        0.80731843],
       [0.20837178, 0.4118654 , 0.79140393, ..., 0.49617493, 0.82446438,
        0.4406996 ],
       [0.10821546, 0.24816414, 0.80841571, ..., 0.50032874, 0.79328015,
        0.43347276]])

In [2]:
matB = np.array(np.random.rand(n,n))
matB

array([[0.90730994, 0.27958103, 0.36221511, ..., 0.0647969 , 0.89759645,
        0.63700985],
       [0.20863408, 0.04079617, 0.69592264, ..., 0.65603456, 0.15360854,
        0.74144175],
       [0.93120401, 0.42252376, 0.68590057, ..., 0.79291872, 0.85754378,
        0.64059254],
       ...,
       [0.37561843, 0.98645671, 0.62275156, ..., 0.34857717, 0.55989868,
        0.25251911],
       [0.67686344, 0.23777812, 0.95434106, ..., 0.30347075, 0.86635487,
        0.66480928],
       [0.93851082, 0.8119    , 0.08794619, ..., 0.09095703, 0.2250349 ,
        0.99981912]])

In [3]:
matC = np.array([[0]*n for _ in range(n)])
matC

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]])

In [4]:
matD = np.array([[0]*n for _ in range(n)])
matD

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]])

In [5]:
for i in range(n):
    for j in range(n):
        matD[i][j] = matA[i][j]+matB[i][j]
print(matD)

[[0 1 1 ... 0 0 1]
 [1 1 1 ... 1 1 0]
 [1 0 1 ... 1 1 1]
 ...
 [0 1 1 ... 1 1 1]
 [0 0 1 ... 0 1 1]
 [1 1 0 ... 0 1 1]]


In [6]:
for i in range(n):
    for j in range(n):
        for k in range(n):
            matC[i][j] += matA[i][k]*matB[k][j]
print(matC)

[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]


In [7]:
matC=np.dot(matA, matB)
matC

array([[36.80845252, 41.02278554, 36.46531089, ..., 37.76223403,
        35.15471937, 40.87026978],
       [35.61113649, 37.68720312, 34.89355978, ..., 36.08362874,
        33.21885136, 37.95038939],
       [34.82151992, 39.37172516, 35.84141597, ..., 38.28672814,
        34.12863947, 38.596919  ],
       ...,
       [37.36630991, 43.15695619, 37.68006788, ..., 40.55148521,
        35.58957099, 41.76951976],
       [38.6289178 , 42.66597046, 39.78146083, ..., 38.87337043,
        37.27060117, 43.6877856 ],
       [33.03688863, 36.11430597, 34.43677455, ..., 33.68851017,
        31.63817127, 37.21581319]])