In [1]:
import numpy as np

# numpy의 random
1. rand()
2. randn()
3. randint()
4. seed()
5. choice()

## rand()
- 0~1사이의 분포딘 랜덤한 ndarray를 생성

In [2]:
x= np.random.rand(10)
print(x)
print()
y= np.random.rand(2,2)
print(y)
print()
z= np.random.rand(2,2,2)
print(z)
print()

[0.29654355 0.33630474 0.9779403  0.66110511 0.22248257 0.51666646
 0.44459157 0.41830852 0.19857624 0.56498279]

[[0.57234271 0.46335064]
 [0.47453111 0.34055298]]

[[[0.29147452 0.23198966]
  [0.97918443 0.14643661]]

 [[0.86180077 0.35401624]
  [0.00639164 0.86373241]]]



## randn(n)
- n에대한 정규분포로 샘플링된 랜덤 ndarray생성

In [3]:
x=np.random.randn(5,5)
print(x)

[[ 0.38099419 -1.46354214  0.97524592 -0.55950235  1.31244124]
 [ 0.29456912 -0.77219984 -1.46677396  0.01773997 -1.01324895]
 [-0.26892613  0.07394834 -0.20582514  0.19947114  0.72677272]
 [ 1.86509941  1.01840165 -1.5346861   0.57131751 -0.33762941]
 [ 0.3841454   0.90376534 -0.74443374  1.2229129   1.72353042]]


## randint()

In [4]:
x= np.random.randint(1,100, size=(5,5))
print(x)

[[57 11 15 45 13]
 [60 43 86 75  5]
 [16 48 97 83 21]
 [ 9 92 97 83 44]
 [60  9 95 54 93]]


## seed(n)
- n은 크게 상관이없다 꼬리표같은것, 저장할갯수등이 아니다.
- 랜덤으로 출력한값을 기억하고 싶을때,

In [24]:
np.random.seed(25)
x=np.random.randn(5,5)
print(x)

[[ 0.22827309  1.0268903  -0.83958485 -0.59118152 -0.9568883 ]
 [-0.22232569 -0.61991511  1.83790458 -2.05323076  0.86858305]
 [-0.92073444 -0.23231186  2.1529569  -1.33466147  0.07637965]
 [-1.24608928  1.20227231 -1.04994158  1.05661011 -0.41967767]
 [ 2.29484234 -2.59448738  2.8227564   0.68088892 -1.57769345]]


## choice()

In [29]:
x=np.arange(1,10,0.5)
print(x)
y=np.random.choice(x, size=(3,3),replace=True)#replace옵션값때문에 중복이된다, 중복 비허용=False
print(y)

[1.  1.5 2.  2.5 3.  3.5 4.  4.5 5.  5.5 6.  6.5 7.  7.5 8.  8.5 9.  9.5]
[[9.5 8.  3.5]
 [6.  8.  4.5]
 [8.5 8.  7. ]]


In [33]:
z=np.random.choice(100, size=(7,7))
print(z)

[[99 23 80 16 76 25 52]
 [ 4 86 87 29 64 50 22]
 [64 92  0 20 99 64 46]
 [15 65  2 65  0  3 54]
 [44 17 65 18 14  8 63]
 [74 87 64 98 89 25  5]
 [ 7 23 50 13 96 94 94]]
