# Numpy의 슬라이싱
- 리스트, 문자에서의 슬라이싱과 동일한 개념으로 사용
- ','를 사용해서 각차원별로 슬라이싱 가능

In [1]:
# 1차원 벡터의 슬라이싱
x=np.arange(10)
print(x)

[0 1 2 3 4 5 6 7 8 9]


In [2]:
print(x[3:6])

[3 4 5]


In [3]:
print(x[3:8:2])

[3 5 7]


In [6]:
#2차원 행렬에서의 슬라이싱
x=np.arange(10).reshape(2,5)
print(x)
print(x[:,1:4]) #앞 : 행슬라이싱, 뒤 : 열슬라이싱

[[0 1 2 3 4]
 [5 6 7 8 9]]
[[1 2 3]
 [6 7 8]]


In [7]:
#3차원 텐서에서의 슬라이싱
x=np.arange(54).reshape(2,9,3)
print(x)

[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]
  [ 9 10 11]
  [12 13 14]
  [15 16 17]
  [18 19 20]
  [21 22 23]
  [24 25 26]]

 [[27 28 29]
  [30 31 32]
  [33 34 35]
  [36 37 38]
  [39 40 41]
  [42 43 44]
  [45 46 47]
  [48 49 50]
  [51 52 53]]]


In [10]:
print(x[0,0:2,0:3])

[[0 1 2]
 [3 4 5]]


In [12]:
print(x[:1,:2,:])#슬라이싱

[[[0 1 2]
  [3 4 5]]]


In [13]:
print(x[0,:2,:])#인덱싱

[[0 1 2]
 [3 4 5]]


In [15]:
x=np.arange(30).reshape(2,3,5)
print(x)

[[[ 0  1  2  3  4]
  [ 5  6  7  8  9]
  [10 11 12 13 14]]

 [[15 16 17 18 19]
  [20 21 22 23 24]
  [25 26 27 28 29]]]


In [16]:
y=x.flatten()
print(y)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29]


In [19]:
z=x.ravel()
print(z)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29]


In [21]:
zz=np.ravel(x)
print(zz)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29]
