## 선형대수

## 역행렬
### 존재유무판별 np.linalg.det()

In [1]:
import numpy as np

In [2]:
x= np.array([[1,2],[3,4]])
print(np.linalg.det(x)) #결과값이 0이아니면 역행력은 존재한다.

-2.0000000000000004


### 역행렬 구하기

In [3]:
x= np.arange(4).reshape(2,2)
print(x)

[[0 1]
 [2 3]]


In [4]:
inv_x=np.linalg.inv(x)
print(inv_x)

[[-1.5  0.5]
 [ 1.   0. ]]


In [5]:
print(np.dot(x,inv_x))

[[1. 0.]
 [0. 1.]]


### 고유값 : 정방행렬 A에대하여  Ax =λx (λ=상수) 가 성립하는 0이아닌 벡터 x가 존재할 때 상수 λ를 A의 고유값(eigenvalue)이라한다
### 고유벡터 : x를 이에 대응하는 고유벡터(eigenvector)
### np.linalg.eig() -> w(고유값),v(고유벡터)

In [8]:
x=np.array([[4,2],[3,3]])
print(x)

[[4 2]
 [3 3]]


In [9]:
w,v=np.linalg.eig(x)
print(w)
print(v)

[6. 1.]
[[ 0.70710678 -0.5547002 ]
 [ 0.70710678  0.83205029]]


### 특이값(Singual Value Decomposition)
### 특이값 분해는 고유값 분해(eigen decomposition)처럼 행렬을 대각화하는 한 방법으로써, 정방행렬뿐만 아이라 모든 m x n 행렬에 대해 적용 가능

In [11]:
x = np.array([[3,6],[2,3],[0,0],[0,0]])
x

array([[3, 6],
       [2, 3],
       [0, 0],
       [0, 0]])

In [12]:
u,s,vh=np.linalg.svd(x)
print(u)
print(s)
print(vh)

[[-0.8816746  -0.47185793  0.          0.        ]
 [-0.47185793  0.8816746   0.          0.        ]
 [ 0.          0.          1.          0.        ]
 [ 0.          0.          0.          1.        ]]
[7.60555128 0.39444872]
[[-0.47185793 -0.8816746 ]
 [ 0.8816746  -0.47185793]]


## 연립 방정식의 해 np.linalg.solve(a,b)

>4x + 3y = 23  
>3x + 2y = 16

In [13]:
a=np.array([[4,3],[3,2]])
b=np.array([23,16])
x=np.linalg.solve(a,b)
print(x)

[2. 5.]


>x+y=25  
>2x+4y=64

In [15]:
a=np.array([[1,1],[2,4]])
b=np.array([25,64])
x=np.linalg.solve(a,b)
print(x)

[18.  7.]
