In [1]:
import numpy as np

# ravel, np.ravel
- 다차원 배열을 1차원으로 변경

In [5]:
x = np.arange(10).reshape(2,5)
print(x)

[[0 1 2 3 4]
 [5 6 7 8 9]]


In [6]:
y=np.ravel(x)
print(y)

[0 1 2 3 4 5 6 7 8 9]


In [7]:
y=np.ravel(x, order='F')#order옵션을 통해서 row(C)우선인지 coulmn(F)우선인지결정
print(y)

[0 5 1 6 2 7 3 8 4 9]


In [8]:
z=np.ravel(x, order='C')#order옵션을 통해서 row(C)우선인지 coulmn(F)우선인지결정
print(z)

[0 1 2 3 4 5 6 7 8 9]


In [9]:
temp=x.ravel()##이와같이 자료형에대해 ravel을 참조연산자로시행하면 서로데이터를 참조한다
print(temp)

[0 1 2 3 4 5 6 7 8 9]


In [10]:
temp[0]=100
print(x)

[[100   1   2   3   4]
 [  5   6   7   8   9]]


# flatten함수 (ravel함수와 비교가 되는함수)
- 다차원을 1차원으로 변경
- 새로운 값을 반환하기 때문에 서로 참조하지 아니한다.

In [11]:
x=np.arange(10).reshape(2,5)
print(x)
y=x.flatten()
print(y)

[[0 1 2 3 4]
 [5 6 7 8 9]]
[0 1 2 3 4 5 6 7 8 9]


In [12]:
z=x.flatten(order='F')
print(z)

[0 5 1 6 2 7 3 8 4 9]


# reshape 함수
- array의 shape를 다른차원으로 변경
- reshape를 사용하기위해선 예상되는 결과의 요수의 수가 변환하려는 값의 요소의 수와 같아야한다.

In [13]:
x=np.arange(36)
print(x)
print(x.shape)
print(x.ndim)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35]
(36,)
1


In [14]:
y=x.reshape(6,6)
print(y)
print(y.shape)
print(y.ndim)

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]
 [24 25 26 27 28 29]
 [30 31 32 33 34 35]]
(6, 6)
2


In [15]:
z=x.reshape(4,-1)
print(z)

[[ 0  1  2  3  4  5  6  7  8]
 [ 9 10 11 12 13 14 15 16 17]
 [18 19 20 21 22 23 24 25 26]
 [27 28 29 30 31 32 33 34 35]]


In [17]:
zz=x.reshape(3,3,4)
print(zz)
print(zz.shape)
print(zz.ndim)

[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]

 [[24 25 26 27]
  [28 29 30 31]
  [32 33 34 35]]]
(3, 3, 4)
3
