# numpy 생성

## np.array()

In [1]:
import numpy as np

x= np.array([1,2,3,4])
print(type(x))
print(x.shape)
x#벡터

<class 'numpy.ndarray'>
(4,)


array([1, 2, 3, 4])

In [2]:
y=np.array([[2,3,4],[1,3,5]])
print(type(y))
print(y.shape)
y#행렬

<class 'numpy.ndarray'>
(2, 3)


array([[2, 3, 4],
       [1, 3, 5]])

In [3]:
z=np.array([[[1,2,],[3,4]],[[5,6],[7,8]]])
print(type(z))
print(z.shape)
z#텐서

<class 'numpy.ndarray'>
(2, 2, 2)


array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

## np.arange()

In [4]:
x=np.arange(1, 10)
print(x)
x=np.arange(1,10,2)
x

[1 2 3 4 5 6 7 8 9]


array([1, 3, 5, 7, 9])

## np.ones()
* 1 또는 0 으로 채우기

In [5]:
x=np.ones(3)
print(x)
print('---')
y=np.ones((3,3))
print(y)
print('---')
z=np.ones((3,3,3))
print(z)

[1. 1. 1.]
---
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
---
[[[1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]]]


## np.zeros
- 0으로채우기

In [6]:
x=np.zeros(3)
print(x)
print('---')
y=np.zeros((3,3))
print(y)
print('---')
z=np.zeros((3,3,3))
print(z)

[0. 0. 0.]
---
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
---
[[[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]]


## np.empty()

In [7]:
x=np.empty(3)
print(x)
print('---')
y=np.empty((3,3))
print(y)
print('---')
z=np.empty((3,3,3))
print(z)

[0. 0. 0.]
---
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
---
[[[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]]


## np.full
- 특정한 값으로 채움

In [9]:
x=np.full((3),1)
print(x)
print('---')
y=np.full((3,3),2)
print(y)
print('---')
z=np.full((3,3,3),3)
print(z)

[1 1 1]
---
[[2 2 2]
 [2 2 2]
 [2 2 2]]
---
[[[3 3 3]
  [3 3 3]
  [3 3 3]]

 [[3 3 3]
  [3 3 3]
  [3 3 3]]

 [[3 3 3]
  [3 3 3]
  [3 3 3]]]


## np.eye()
- 단위행렬을 만듦( E 행렬)

In [10]:
x=np.eye(5)
print(x)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


## np.linspace(start,end,range)
- 등차수열(a1~an,n) n=항의개수
- d값은 알아서 계산해서 적용해줌

In [11]:
x = np.linspace(1, 10, 4)
y = np.linspace(1, 10 ,3)
print(x)
print(y)

[ 1.  4.  7. 10.]
[ 1.   5.5 10. ]


## reshape 함수
- ndarray의 차원을 바꾸기 위해 사용
- 바꾸고자하는 데이터의 갯수가 일치해야한다

In [14]:
x = np.arange(1,16)
print(x)
print(x.shape)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15]
(15,)


In [16]:
y=x.reshape(3,5)
print(y)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]]
