In [5]:
import numpy as np

df=np.random.randint(0,2,(10,10))

In [6]:
print(df)

[[1 0 1 0 0 0 0 1 0 0]
 [0 1 0 0 0 0 1 1 0 0]
 [0 1 1 0 0 1 1 0 0 0]
 [1 0 1 1 0 1 1 0 0 0]
 [1 0 0 0 0 1 1 1 1 0]
 [1 0 1 0 0 0 0 0 0 0]
 [1 0 0 1 1 1 0 0 1 1]
 [0 0 0 1 1 1 1 0 0 0]
 [1 0 0 1 0 0 1 0 0 0]
 [0 1 0 1 1 0 1 0 0 0]]


In [7]:
print(df[df>0])

[1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1]
